<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="95405" started-at="2019-03-29T08:55:40Z" finished-at="2019-03-29T08:57:15Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="95405" started-at="2019-03-29T08:55:40Z" finished-at="2019-03-29T08:57:15Z">
      <class name="Tests.LoginPageTestCase">
        <test-method status="FAIL" signature="addNewCustomer()[pri:0, instance:Tests.LoginPageTestCase@457e2f02]" name="addNewCustomer" duration-ms="31" started-at="2019-03-29T14:25:40Z" finished-at="2019-03-29T14:25:40Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.gurudemositelogin.Page.HomePage.navigateToNewCustomerScreen(HomePage.java:28)
	at Tests.LoginPageTestCase.addNewCustomer(LoginPageTestCase.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCustomer -->
        <test-method status="PASS" signature="checkValidLogin()[pri:0, instance:Tests.LoginPageTestCase@457e2f02]" name="checkValidLogin" duration-ms="95344" started-at="2019-03-29T14:25:40Z" finished-at="2019-03-29T14:27:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkValidLogin -->
      </class> <!-- Tests.LoginPageTestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
